spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # User Service route
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            # Auth Service route
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
    instance-id: ${spring.application.name}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

jwt:
  secret: ${JWT_SECRET:bXktdmVyeS1zdHJvbmctand0LXNlY3JldC1rZXktZm9yLWF1dGgtc2VydmljZS0yMDI2}